
func test (Int a, Int b) -> Int | DivByZeroErr {
    // Can return an error
    if b == 0 {
        return DivByZeroErr("b is zero")
    }
    return a / b
}

func okay (Int x) -> Int | . {
    // no error
    return x * x
}

func main () -> Void | Err {
    let a = "abcd"
    println(a)
    mut b = 0
    b = 1
    println(b)
    
    mut ret = test(1, 2) // No error
    if ?ret {
        return Err // General purpose error
    } else {
        print("Everything's alright")
    }

    ret = okay(2)  // No need to check for errors
} 
